### PR TITLE
Updated Webpack Plugin to be compatible with Webpack 4 (fixes #47)

### LINKED ISSUE #47: Webpack 4 support
We have noticed that with webpack 4 there is a DeprecationWarning for the plugin.

```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on ``.hooks`` instead`
`at WebpackBundleSizeAnalyzerPlugin.apply (.\node_modules\webpack-bundle-size-analyzer\build\src\plugin.js:15:18)
```

According to that [comment](https://github.com/webpack/webpack/issues/6568#issuecomment-377491754) the changes should be done here.

### PR DESCRIPTION
**Pull request by spiltcoffee**

### CODE REVIEW

**Comment by robertknight** [comment]
Can you confirm if this change is backwards compatible with older versions of webpack and if so, how far back it is compatible? If it works with webpack v4+ only then we could still merge this but should also bump the major version of the package and make a note in the changelog.

**Comment by spiltcoffee** [comment]
My understanding is that this was a breaking change in Webpack 4, so I assume this change would break the plugin for all versions less than Webpack 4.

It might be possible to supply backwards compatibility [according to this](https://blog.johnnyreilly.com/2018/01/finding-webpack-4-use-map.html), but it requires additional work (and testing) on top of this pull request.

**Comment by robertknight** [comment]
OK, in that case I can merge this as is but will bump the package version to 3.0.0 and make a note in the changelog that the plugin requires Webpack 4.x+. Anyone who is using an older version of Webpack can use an earlier 2.x release.

**Comment by robertknight** [comment]
Published as v3.0.0.

**Comment by spiltcoffee** [comment]
So I know this is pulled in now and v3.0.0 is out there now, but I just stumbled across this pull request: vuejs/vue#7839

The changes in that pull request to util.js show how you could possibly go about providing backwards compatibility if that's something that you still desire.

**Comment by robertknight** [comment]
Thanks for following up on that question. I'll wait until someone asks for it 😛

**Pull request merged**
